---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    server: "*"
  register: r_osp_servers

- name: Delete instances
  os_server:
    name: "{{ item }}"
    state: absent
    delete_fip: yes
  loop: "{{ r_osp_servers.openstack_servers }}"
   
