---

- name: Install tomcat
  yum:
    name: "{{ payload }}"
    state: latest

- name: Create tomcat directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
    mode: '0755'

- name: Create index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: '0644'

- name: Create tomcat service
  service:
    name: "{{ payload }}"
    enabled: yes
  notify:
    "start {{ payload }}"
